name: GLaDOS定时签到
on:
  schedule: # Actions自动运行，自动签到时间，cron表达式，不会的看README
    - cron: "39 04 * * *" # 分 时 日 月 星期，请修改为其它随机时间，大概有8h+的延迟
    
  push:
    branches: ["main"]
    paths:  
      - '.github/workflows/*'

jobs:
  GLaDOS-CheckIn:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      - name: 准备 node 环境
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 安装依赖
        run: |
          npm i
      - name: 开始签到
        env:
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          SERVER_TOKEN: ${{ secrets.SENDKEY }}
        run: |
          node ./index.js